SET IDENTITY_INSERT [dbo].[TIPO_UBICACION_CATASTRAL] ON
INSERT [dbo].[TIPO_UBICACION_CATASTRAL] ([ID_TIPO_UBICACION_CATASTRAL], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), N'CATASTRAL')
INSERT [dbo].[TIPO_UBICACION_CATASTRAL] ([ID_TIPO_UBICACION_CATASTRAL], [DESCRIPCION]) VALUES (CAST(2 AS Numeric(19, 0)), N'OFICIAL')
SET IDENTITY_INSERT [dbo].[TIPO_UBICACION_CATASTRAL] OFF

SET IDENTITY_INSERT [dbo].[TIPO_SUMINISTRO] ON
INSERT [dbo].[TIPO_SUMINISTRO] ([ID_TIPO_SUMINISTRO], [DESCRIPCION], [IMPORTE]) VALUES (CAST(1 AS Numeric(19, 0)), N'FAMILIAR', 60.7)
INSERT [dbo].[TIPO_SUMINISTRO] ([ID_TIPO_SUMINISTRO], [DESCRIPCION], [IMPORTE]) VALUES (CAST(2 AS Numeric(19, 0)), N'COMERCIAL', 100.92)
SET IDENTITY_INSERT [dbo].[TIPO_SUMINISTRO] OFF

SET IDENTITY_INSERT [dbo].[TIPO_DOMICILIO] ON
INSERT [dbo].[TIPO_DOMICILIO] ([ID_TIPO_DOMICILIO], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), N'LEGAL')
INSERT [dbo].[TIPO_DOMICILIO] ([ID_TIPO_DOMICILIO], [DESCRIPCION]) VALUES (CAST(2 AS Numeric(19, 0)), N'SERVICIO')
INSERT [dbo].[TIPO_DOMICILIO] ([ID_TIPO_DOMICILIO], [DESCRIPCION]) VALUES (CAST(3 AS Numeric(19, 0)), N'FACTURACION')
SET IDENTITY_INSERT [dbo].[TIPO_DOMICILIO] OFF

SET IDENTITY_INSERT [dbo].[TIPO_DOCUMENTO] ON
INSERT [dbo].[TIPO_DOCUMENTO] ([ID_TIPO_DOC], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), N'DU DOCUMENTO ÚNICO')
INSERT [dbo].[TIPO_DOCUMENTO] ([ID_TIPO_DOC], [DESCRIPCION]) VALUES (CAST(2 AS Numeric(19, 0)), N'LE LIBRETA DE ENROLAMIENTO')
INSERT [dbo].[TIPO_DOCUMENTO] ([ID_TIPO_DOC], [DESCRIPCION]) VALUES (CAST(3 AS Numeric(19, 0)), N'LC LIBRETA CIVICA')
INSERT [dbo].[TIPO_DOCUMENTO] ([ID_TIPO_DOC], [DESCRIPCION]) VALUES (CAST(4 AS Numeric(19, 0)), N'CI CEDULA')
INSERT [dbo].[TIPO_DOCUMENTO] ([ID_TIPO_DOC], [DESCRIPCION]) VALUES (CAST(5 AS Numeric(19, 0)), N'PA PASAPORTE')
INSERT [dbo].[TIPO_DOCUMENTO] ([ID_TIPO_DOC], [DESCRIPCION]) VALUES (CAST(6 AS Numeric(19, 0)), N'CUIL')
INSERT [dbo].[TIPO_DOCUMENTO] ([ID_TIPO_DOC], [DESCRIPCION]) VALUES (CAST(7 AS Numeric(19, 0)), N'CUIT')
SET IDENTITY_INSERT [dbo].[TIPO_DOCUMENTO] OFF

SET IDENTITY_INSERT [dbo].[TIPO_CONEXION] ON
INSERT [dbo].[TIPO_CONEXION] ([ID_TIPO_CONEXION], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), N'MEDIDOR')
INSERT [dbo].[TIPO_CONEXION] ([ID_TIPO_CONEXION], [DESCRIPCION]) VALUES (CAST(2 AS Numeric(19, 0)), N'LIMITADOR')
SET IDENTITY_INSERT [dbo].[TIPO_CONEXION] OFF

SET IDENTITY_INSERT [dbo].[TIPO_CATEGORIA_CONEXION] ON
INSERT [dbo].[TIPO_CATEGORIA_CONEXION] ([ID_TIPO_CATEGORIA_CONEXION], [DESCRIPCION]) VALUES (CAST(12 AS Numeric(19, 0)), N'NORMAL')
INSERT [dbo].[TIPO_CATEGORIA_CONEXION] ([ID_TIPO_CATEGORIA_CONEXION], [DESCRIPCION]) VALUES (CAST(10 AS Numeric(19, 0)), N'CANON')
INSERT [dbo].[TIPO_CATEGORIA_CONEXION] ([ID_TIPO_CATEGORIA_CONEXION], [DESCRIPCION]) VALUES (CAST(3 AS Numeric(19, 0)), N'NUEVA')
SET IDENTITY_INSERT [dbo].[TIPO_CATEGORIA_CONEXION] OFF

SET IDENTITY_INSERT [dbo].[FORMA_PAGO] ON
INSERT [dbo].[FORMA_PAGO] ([ID_FORMA_PAGO], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), N'EFECTIVO')
INSERT [dbo].[FORMA_PAGO] ([ID_FORMA_PAGO], [DESCRIPCION]) VALUES (CAST(2 AS Numeric(19, 0)), N'TARJETA NARANJA')
INSERT [dbo].[FORMA_PAGO] ([ID_FORMA_PAGO], [DESCRIPCION]) VALUES (CAST(3 AS Numeric(19, 0)), N'DEPOSITO/TRANSFERENCIA BANCARIA')
SET IDENTITY_INSERT [dbo].[FORMA_PAGO] OFF

SET IDENTITY_INSERT [dbo].[REGIMEN_PROPIEDAD] ON
INSERT [dbo].[REGIMEN_PROPIEDAD] ([ID_REGIMEN_PROPIEDAD], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), N'PROPIETARIO')
INSERT [dbo].[REGIMEN_PROPIEDAD] ([ID_REGIMEN_PROPIEDAD], [DESCRIPCION]) VALUES (CAST(2 AS Numeric(19, 0)), N'INQUILINO')
INSERT [dbo].[REGIMEN_PROPIEDAD] ([ID_REGIMEN_PROPIEDAD], [DESCRIPCION]) VALUES (CAST(3 AS Numeric(19, 0)), N'OCUPANTE')
SET IDENTITY_INSERT [dbo].[REGIMEN_PROPIEDAD] OFF

SET IDENTITY_INSERT [dbo].[PROVINCIAS] ON
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), N'CORDOBA')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(2 AS Numeric(19, 0)), N'BUENOS AIRES')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(3 AS Numeric(19, 0)), N'CATAMARCA')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(4 AS Numeric(19, 0)), N'CHACO')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(5 AS Numeric(19, 0)), N'CHUBUT')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(6 AS Numeric(19, 0)), N'CORRIENTES')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(7 AS Numeric(19, 0)), N'ENTRE RIOS')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(8 AS Numeric(19, 0)), N'FORMOSA')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(9 AS Numeric(19, 0)), N'JUJUY')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(10 AS Numeric(19, 0)), N'LA PAMPA')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(11 AS Numeric(19, 0)), N'LA RIOJA')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(12 AS Numeric(19, 0)), N'MENDOZA')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(13 AS Numeric(19, 0)), N'MISIONES')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(14 AS Numeric(19, 0)), N'NEUQUEN')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(15 AS Numeric(19, 0)), N'RIO NEGRO')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(16 AS Numeric(19, 0)), N'SALTA')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(17 AS Numeric(19, 0)), N'SAN JUAN')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(18 AS Numeric(19, 0)), N'SAN LUIS')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(19 AS Numeric(19, 0)), N'SANTA CRUZ')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(20 AS Numeric(19, 0)), N'SANTA FE')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(21 AS Numeric(19, 0)), N'SANTIAGO DEL ESTERO')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(22 AS Numeric(19, 0)), N'TIERRA DEL FUEGO')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(23 AS Numeric(19, 0)), N'TUCUMAN')
INSERT [dbo].[PROVINCIAS] ([ID_PROVINCIA], [DESCRIPCION]) VALUES (CAST(24 AS Numeric(19, 0)), N'OTROS')
SET IDENTITY_INSERT [dbo].[PROVINCIAS] OFF

SET IDENTITY_INSERT [dbo].[CONDICION_IVA] ON
INSERT [dbo].[CONDICION_IVA] ([ID_CONDICION_IVA], [ABREVIATURA], [DESCRIPCION], [PORCENTAJE], [IVA_OTROS_CONCEPTOS]) VALUES (1, N'S/I', N'SIN INFORMAR', 21, NULL)
INSERT [dbo].[CONDICION_IVA] ([ID_CONDICION_IVA], [ABREVIATURA], [DESCRIPCION], [PORCENTAJE], [IVA_OTROS_CONCEPTOS]) VALUES (2, N'CF', N'CONSUMIDOR FINAL', 21, NULL)
INSERT [dbo].[CONDICION_IVA] ([ID_CONDICION_IVA], [ABREVIATURA], [DESCRIPCION], [PORCENTAJE], [IVA_OTROS_CONCEPTOS]) VALUES (3, N'R/N INSC', N'RESPONSABLE NO INSCRIPTO', 27, NULL)
INSERT [dbo].[CONDICION_IVA] ([ID_CONDICION_IVA], [ABREVIATURA], [DESCRIPCION], [PORCENTAJE], [IVA_OTROS_CONCEPTOS]) VALUES (4, N'R INSC', N'RESPONSABLE INSCRIPTO', 27, NULL)
INSERT [dbo].[CONDICION_IVA] ([ID_CONDICION_IVA], [ABREVIATURA], [DESCRIPCION], [PORCENTAJE], [IVA_OTROS_CONCEPTOS]) VALUES (5, N'EX', N'EXENTO', 21, NULL)
INSERT [dbo].[CONDICION_IVA] ([ID_CONDICION_IVA], [ABREVIATURA], [DESCRIPCION], [PORCENTAJE], [IVA_OTROS_CONCEPTOS]) VALUES (6, N'NO RESP', N'NO RESPONSABLE', 27, NULL)
INSERT [dbo].[CONDICION_IVA] ([ID_CONDICION_IVA], [ABREVIATURA], [DESCRIPCION], [PORCENTAJE], [IVA_OTROS_CONCEPTOS]) VALUES (7, N'MONO T', N'MONOTRIBUTO', 27, NULL)
INSERT [dbo].[CONDICION_IVA] ([ID_CONDICION_IVA], [ABREVIATURA], [DESCRIPCION], [PORCENTAJE], [IVA_OTROS_CONCEPTOS]) VALUES (8, N'NO CAT', N'NO CATEGORIZADO', 40, NULL)
SET IDENTITY_INSERT [dbo].[CONDICION_IVA] OFF


SET IDENTITY_INSERT [dbo].[CONCEPTO_FACTURACION] ON
INSERT [dbo].[CONCEPTO_FACTURACION] ([ID], [ALICUOTA_IVA], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), 21, N'SERVICIO AGUA')
SET IDENTITY_INSERT [dbo].[CONCEPTO_FACTURACION] OFF


SET IDENTITY_INSERT [dbo].[CONFIGURACION_FACTURAS] ON
INSERT [dbo].[CONFIGURACION_FACTURAS] ([ID_CONFIGURACION_FACT], [CAPITAL_SOCIAL], [CARGO_FIJO], [ERSEP], [IMPRESION_Y_OTROS], [LEYENDA_COMPROBANTE], [RECUPERO_INVERSION], [TRAMO_1], [TRAMO_2], [TRAMO_3], [TRAMO_4], [TRAMO_5], [TRAMO_6]) VALUES (CAST(3 AS Numeric(19, 0)), 5, 0, 1.2, 7, N'CONFIGURACION', 5, 0.27, 0.41, 2.64, 3.7, 4.26, 6.38)
SET IDENTITY_INSERT [dbo].[CONFIGURACION_FACTURAS] OFF


SET IDENTITY_INSERT [dbo].[PERIODO_CANON] ON
INSERT [dbo].[PERIODO_CANON] ([PERIODO_CANON_ID], [ANIO], [MES]) VALUES (CAST(2 AS Numeric(19, 0)), 2016, 4)
INSERT [dbo].[PERIODO_CANON] ([PERIODO_CANON_ID], [ANIO], [MES]) VALUES (CAST(4 AS Numeric(19, 0)), 2016, 8)
INSERT [dbo].[PERIODO_CANON] ([PERIODO_CANON_ID], [ANIO], [MES]) VALUES (CAST(5 AS Numeric(19, 0)), 2016, 12)
SET IDENTITY_INSERT [dbo].[PERIODO_CANON] OFF


SET IDENTITY_INSERT [dbo].[PAISES] ON
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (1,'Argentina'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (7,'Estados Unidos'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (3,'Albania'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (4,'Alemania'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (5,'Andorra'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (6,'Angola'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (2,'Anguila'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (8,'Antártida'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (9,'Antigua y Barbuda'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (10,'Antillas Neerlandesas'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (11,'Arabia Saudí'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (12,'Arctic Ocean'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (13,'Argelia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (14,'Afganistán'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (15,'Armenia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (16,'Aruba'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (17,'Ashmore andCartier Islands'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (18,'Atlantic Ocean'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (19,'Australia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (20,'Austria'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (21,'Azerbaiyán'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (22,'Bahamas'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (23,'Bahráin'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (24,'Bangladesh'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (25,'Barbados'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (26,'Bélgica'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (27,'Belice'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (28,'Benín'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (29,'Bermudas'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (30,'Bielorrusia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (31,'Birmania Myanmar'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (32,'Bolivia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (33,'Bosnia y Hercegovina'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (34,'Botsuana'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (35,'Brasil'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (36,'Brunéi'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (37,'Bulgaria'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (38,'Burkina Faso'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (39,'Burundi'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (40,'Bután'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (41,'Cabo Verde'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (42,'Camboya'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (43,'Camerún'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (44,'Canadá'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (45,'Chad'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (46,'Chile'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (47,'China'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (48,'Chipre'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (49,'Clipperton Island'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (50,'Colombia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (51,'Comoras'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (52,'Congo'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (53,'Coral Sea Islands'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (54,'Corea del Norte'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (55,'Corea del Sur'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (56,'Costa de Marfil'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (57,'Costa Rica'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (58,'Croacia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (59,'Cuba'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (60,'Dhekelia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (61,'Dinamarca'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (62,'Dominica'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (63,'Ecuador'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (64,'Egipto'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (65,'El Salvador'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (66,'El Vaticano'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (67,'Emiratos Árabes Unidos'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (68,'Eritrea'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (69,'Eslovaquia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (70,'Eslovenia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (71,'España'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (72,'Akrotiri'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (73,'Estonia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (74,'Etiopía'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (75,'Filipinas'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (76,'Finlandia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (77,'Fiyi'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (78,'Francia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (79,'Gabón'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (80,'Gambia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (81,'Gaza Strip'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (82,'Georgia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (83,'Ghana'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (84,'Gibraltar'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (85,'Granada'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (86,'Grecia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (87,'Groenlandia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (88,'Guam'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (89,'Guatemala'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (90,'Guernsey'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (91,'Guinea'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (92,'Guinea Ecuatorial'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (93,'Guinea-Bissau'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (94,'Guyana'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (95,'Haití'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (96,'Honduras'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (97,'Hong Kong'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (98,'Hungría'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (99,'India'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (100,'Indian Ocean'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (101,'Indonesia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (102,'Irán'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (103,'Iraq'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (104,'Irlanda'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (105,'Isla Bouvet'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (106,'Isla Christmas'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (107,'Isla Norfolk'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (108,'Islandia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (109,'Islas Caimán'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (110,'Islas Cocos'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (111,'Islas Cook'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (112,'Islas Feroe'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (113,'Islas Georgia del Sur y Sandwich del Sur'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (114,'Islas Heard y McDonald'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (115,'Islas Malvinas'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (116,'Islas Marianas del Norte'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (117,'IslasMarshall'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (118,'Islas Pitcairn'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (119,'Islas Salomón'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (120,'Islas Turcas y Caicos'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (121,'Islas Vírgenes Americanas'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (122,'Islas Vírgenes Británicas'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (123,'Israel'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (124,'Italia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (125,'Jamaica'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (126,'Jan Mayen'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (127,'Japón'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (128,'Jersey'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (129,'Jordania'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (130,'Kazajistán'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (131,'Kenia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (132,'Kirguizistán'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (133,'Kiribati'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (134,'Kuwait'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (135,'Laos'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (136,'Lesoto'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (137,'Letonia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (138,'Líbano'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (139,'Liberia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (140,'Libia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (141,'Liechtenstein'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (142,'Lituania'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (143,'Luxemburgo'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (144,'Macao'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (145,'Macedonia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (146,'Madagascar'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (147,'Malasia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (148,'Malaui'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (149,'Maldivas'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (150,'Malí'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (151,'Malta'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (152,'Man, Isle of'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (153,'Marruecos'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (154,'Mauricio'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (155,'Mauritania'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (156,'Mayotte'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (157,'México'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (158,'Micronesia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (159,'Moldavia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (160,'Mónaco'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (161,'Mongolia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (162,'Montserrat'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (163,'Mozambique'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (164,'Namibia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (165,'Nauru'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (166,'Navassa Island'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (167,'Nepal'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (168,'Nicaragua'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (169,'Níger'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (170,'Nigeria'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (171,'Niue'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (172,'Noruega'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (173,'Nueva Caledonia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (174,'Nueva Zelanda'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (175,'Omán'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (176,'Pacific Ocean'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (177,'Países Bajos'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (178,'Pakistán'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (179,'Palaos'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (180,'Panamá'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (181,'Papúa-Nueva Guinea'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (182,'Paracel Islands'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (183,'Paraguay'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (184,'Perú'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (185,'Polinesia Francesa'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (186,'Polonia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (187,'Portugal'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (188,'Puerto Rico'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (189,'Qatar'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (190,'Reino Unido'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (191,'República Centroafricana'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (192,'República Checa'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (193,'República Democrática del Congo'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (194,'República Dominicana'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (195,'Ruanda'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (196,'Rumania'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (197,'Rusia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (198,'Sáhara Occidental'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (199,'Samoa'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (200,'Samoa Americana'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (201,'San Cristóbal y Nieves'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (202,'San Marino'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (203,'San Pedro y Miquelón'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (204,'San Vicente y las Granadinas'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (205,'Santa Helena'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (206,'Santa Lucía'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (207,'Santo Tomé y Príncipe'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (208,'Senegal'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (209,'Seychelles'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (210,'Sierra Leona'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (211,'Singapur'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (212,'Siria'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (213,'Somalia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (214,'Southern Ocean'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (215,'Spratly Islands'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (216,'Sri Lanka'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (217,'Suazilandia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (218,'Sudáfrica'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (219,'Sudán'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (220,'Suecia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (221,'Suiza'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (222,'Surinam'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (223,'Svalbard y Jan Mayen'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (224,'Tailandia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (225,'Taiwán'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (226,'Tanzania'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (227,'Tayikistán'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (228,'TerritorioBritánicodel Océano Indico'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (229,'Territorios Australes Franceses'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (230,'Timor Oriental'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (231,'Togo'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (232,'Tokelau'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (233,'Tonga'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (234,'Trinidad y Tobago'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (235,'Túnez'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (236,'Turkmenistán'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (237,'Turquía'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (238,'Tuvalu'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (239,'Ucrania'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (240,'Uganda'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (241,'Unión Europea'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (242,'Uruguay'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (243,'Uzbekistán'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (244,'Vanuatu'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (245,'Venezuela'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (246,'Vietnam'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (247,'Wake Island'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (248,'Wallis y Futuna'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (249,'West Bank'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (250,'World'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (251,'Yemen'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (252,'Yibuti'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (253,'Zambia'); 
INSERT INTO PAISES (ID_PAIS,DESCRIPCION) VALUES (254,'Zimbabue');
SET IDENTITY_INSERT [dbo].[PAISES] OFF

SET IDENTITY_INSERT [dbo].[ESTADO_SOCIO] ON
INSERT [dbo].[ESTADO_SOCIO] ([ID_ESTADO_SOCIO], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), N'ACTIVO')
INSERT [dbo].[ESTADO_SOCIO] ([ID_ESTADO_SOCIO], [DESCRIPCION]) VALUES (CAST(2 AS Numeric(19, 0)), N'PENDIENTE')
INSERT [dbo].[ESTADO_SOCIO] ([ID_ESTADO_SOCIO], [DESCRIPCION]) VALUES (CAST(3 AS Numeric(19, 0)), N'BAJA')
SET IDENTITY_INSERT [dbo].[ESTADO_SOCIO] OFF


SET IDENTITY_INSERT [dbo].[ESTADO_PERIODO] ON
INSERT [dbo].[ESTADO_PERIODO] ([ESTADO_PERIODO_ID], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), N'EN PROCESO')
INSERT [dbo].[ESTADO_PERIODO] ([ESTADO_PERIODO_ID], [DESCRIPCION]) VALUES (CAST(2 AS Numeric(19, 0)), N'CERRADO')
INSERT [dbo].[ESTADO_PERIODO] ([ESTADO_PERIODO_ID], [DESCRIPCION]) VALUES (CAST(3 AS Numeric(19, 0)), N'FACTURADO')
SET IDENTITY_INSERT [dbo].[ESTADO_PERIODO] OFF


SET IDENTITY_INSERT [dbo].[ESTADO_CONEXIONES] ON
INSERT [dbo].[ESTADO_CONEXIONES] ([ID_ESTADO_CONEXION], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), N'ACTIVA')
INSERT [dbo].[ESTADO_CONEXIONES] ([ID_ESTADO_CONEXION], [DESCRIPCION]) VALUES (CAST(2 AS Numeric(19, 0)), N'CORTADA')
INSERT [dbo].[ESTADO_CONEXIONES] ([ID_ESTADO_CONEXION], [DESCRIPCION]) VALUES (CAST(3 AS Numeric(19, 0)), N'BAJA')
SET IDENTITY_INSERT [dbo].[ESTADO_CONEXIONES] OFF


SET IDENTITY_INSERT [dbo].[ESTADO_CIVIL] ON
INSERT [dbo].[ESTADO_CIVIL] ([ID_ESTADO_CIVIL], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), N'SOLTERO')
INSERT [dbo].[ESTADO_CIVIL] ([ID_ESTADO_CIVIL], [DESCRIPCION]) VALUES (CAST(2 AS Numeric(19, 0)), N'CASADO')
INSERT [dbo].[ESTADO_CIVIL] ([ID_ESTADO_CIVIL], [DESCRIPCION]) VALUES (CAST(3 AS Numeric(19, 0)), N'VIUDO')
INSERT [dbo].[ESTADO_CIVIL] ([ID_ESTADO_CIVIL], [DESCRIPCION]) VALUES (CAST(4 AS Numeric(19, 0)), N'SEPARADO')
INSERT [dbo].[ESTADO_CIVIL] ([ID_ESTADO_CIVIL], [DESCRIPCION]) VALUES (CAST(5 AS Numeric(19, 0)), N'DIVORCIADO')
INSERT [dbo].[ESTADO_CIVIL] ([ID_ESTADO_CIVIL], [DESCRIPCION]) VALUES (CAST(6 AS Numeric(19, 0)), N'CONCOBINO')
SET IDENTITY_INSERT [dbo].[ESTADO_CIVIL] OFF


SET IDENTITY_INSERT [dbo].[USUARIO_TIPOS] ON
INSERT [dbo].[USUARIO_TIPOS] ([TPO_USR_ID], [TPO_USR_CODIGO], [TPO_USR_DESC]) VALUES (CAST(1 AS Numeric(19, 0)), N'SUPER', N'SUPERADMIN')
SET IDENTITY_INSERT [dbo].[USUARIO_TIPOS] OFF


SET IDENTITY_INSERT [dbo].[USUARIOS] ON
INSERT [dbo].[USUARIOS] ([USR_ID], [USR_PASSWORD], [USR_USUARIO], [TPO_USR_ID]) VALUES (CAST(1 AS Numeric(19, 0)), N'92f39f7f2a869838cd5085e6f17fc82109bcf98cd62a47cbc379e38de80bbc0213a23cee6e4a13de6caae0add8a390272d6f0883c274320b1ff60dbcfc6dd750', N'admin', CAST(1 AS Numeric(19, 0)))
SET IDENTITY_INSERT [dbo].[USUARIOS] OFF



SET IDENTITY_INSERT [dbo].[CONFIGURACION_LECTURA] ON
INSERT [dbo].[CONFIGURACION_LECTURA] ([ID_CONF_LECTURA], [FECHA_MOD], [MONTO], [USR_ID]) VALUES (CAST(1 AS Numeric(19, 0)), CAST(0x0000A5B400000000 AS DateTime), CAST(200 AS Numeric(19, 0)), CAST(1 AS Numeric(19, 0)))
SET IDENTITY_INSERT [dbo].[CONFIGURACION_LECTURA] OFF



SET IDENTITY_INSERT [dbo].[ZONAS_CONEXIONES] ON
INSERT [dbo].[ZONAS_CONEXIONES] ([ID_ZONA], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), N'ZONA 1')
INSERT [dbo].[ZONAS_CONEXIONES] ([ID_ZONA], [DESCRIPCION]) VALUES (CAST(2 AS Numeric(19, 0)), N'ZONA 2')
INSERT [dbo].[ZONAS_CONEXIONES] ([ID_ZONA], [DESCRIPCION]) VALUES (CAST(3 AS Numeric(19, 0)), N'ZONA 3')
INSERT [dbo].[ZONAS_CONEXIONES] ([ID_ZONA], [DESCRIPCION]) VALUES (CAST(4 AS Numeric(19, 0)), N'ZONA 4')
INSERT [dbo].[ZONAS_CONEXIONES] ([ID_ZONA], [DESCRIPCION]) VALUES (CAST(5 AS Numeric(19, 0)), N'ZONA 5')
INSERT [dbo].[ZONAS_CONEXIONES] ([ID_ZONA], [DESCRIPCION]) VALUES (CAST(6 AS Numeric(19, 0)), N'ZONA 6')
INSERT [dbo].[ZONAS_CONEXIONES] ([ID_ZONA], [DESCRIPCION]) VALUES (CAST(7 AS Numeric(19, 0)), N'ZONA 7')
INSERT [dbo].[ZONAS_CONEXIONES] ([ID_ZONA], [DESCRIPCION]) VALUES (CAST(8 AS Numeric(19, 0)), N'ZONA 8')
INSERT [dbo].[ZONAS_CONEXIONES] ([ID_ZONA], [DESCRIPCION]) VALUES (CAST(9 AS Numeric(19, 0)), N'ZONA 9')
INSERT [dbo].[ZONAS_CONEXIONES] ([ID_ZONA], [DESCRIPCION]) VALUES (CAST(10 AS Numeric(19, 0)), N'ZONA 10')
SET IDENTITY_INSERT [dbo].[ZONAS_CONEXIONES] OFF



SET IDENTITY_INSERT [dbo].[TIPO_COMPROBANTE] ON
INSERT [dbo].[TIPO_COMPROBANTE] ([ID], [DESCRIPCION]) VALUES (CAST(1 AS Numeric(19, 0)), N'A')
INSERT [dbo].[TIPO_COMPROBANTE] ([ID], [DESCRIPCION]) VALUES (CAST(2 AS Numeric(19, 0)), N'B')
INSERT [dbo].[TIPO_COMPROBANTE] ([ID], [DESCRIPCION]) VALUES (CAST(3 AS Numeric(19, 0)), N'C')
SET IDENTITY_INSERT [dbo].[TIPO_COMPROBANTE] OFF