USE [BASE_DATOS_FAC]
GO

/****** Object:  StoredProcedure [dbo].[SP_SELECT_DATOS]    Script Date: 04/06/2016 02:18:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_SELECT_DATOS] @ANIO INT AS
BEGIN
	SELECT ZONAS_CONEXIONES.*, isnull(SUM(PERIODOS_SALDOS.CONSUMO),0) AS total_consumo, PERIODOS_SALDOS.PERIODO_MES  
	INTO #TEMPORALFINAL
	from ZONAS_CONEXIONES
	INNER JOIN CONEXIONES
		ON ZONAS_CONEXIONES.ID_ZONA = CONEXIONES.ID_NRO_ZONA
	INNER JOIN PERIODOS_SALDOS
		ON PERIODOS_SALDOS.ID_CONEXION = CONEXIONES.ID_CONEXION
	WHERE PERIODOS_SALDOS.PERIODO_ANIO = 2015
	GROUP BY 
		ZONAS_CONEXIONES.ID_ZONA, ZONAS_CONEXIONES.DESCRIPCION, PERIODOS_SALDOS.PERIODO_MES
	ORDER BY ZONAS_CONEXIONES.ID_ZONA ASC, PERIODOS_SALDOS.PERIODO_MES ASC
	
	DECLARE @V int;
	DECLARE @numz int;
	DECLARE @MES INT
	DECLARE @ZONA INT
	DECLARE @TOTAL INT
	declare @sql nvarchar (1000);
	DECLARE @columna varchar(10)
	
	SET @numz =(select MAX(c.ID_NRO_ZONA)from CONEXIONES c);
	SET @V =1;

	CREATE TABLE #TEMPZONA(
    		ZONA INT,
			PER1 INT,
			PER2  INT,
			PER3  INT,
			PER4  INT,
			PER5  INT,
			PER6  INT,
			PER7  INT,
			PER8  INT,
			PER9  INT,
			PER10  INT,
			PER11  INT,
			PER12  INT)
			
	WHILE @V<=@numz
	begin

	INSERT INTO #TEMPZONA
			VALUES (@V,0,0,0,0,0,0,0,0,0,0,0,0)

	set @V=@V+1

	end	
	
	DECLARE CURSOR1 CURSOR FOR 
		SELECT #TEMPORALFINAL.ID_ZONA, 
		#TEMPORALFINAL.PERIODO_MES,
		#TEMPORALFINAL.total_consumo
		FROM  
		#TEMPORALFINAL
		
		
	OPEN CURSOR1
			
		FETCH NEXT FROM CURSOR1
		INTO @ZONA,@MES,@TOTAL
		
		WHILE @@FETCH_STATUS = 0
		BEGIN
		
		SET @columna= N'PER'+convert(varchar(1),@MES);
		
		
		set @sql= N'update #TEMPZONA set [#TEMPZONA].['+@columna+']='+convert(varchar(10),@total)+' where #TEMPZONA.ZONA='+convert(varchar(10),@ZONA);

		exec sp_executesql @sql;

		FETCH NEXT FROM CURSOR1 INTO @ZONA,@MES,@TOTAL
		END
	
		CLOSE CURSOR1
		DEALLOCATE CURSOR1
	
	SELECT * FROM #TEMPZONA t 
	
	DROP TABLE #TEMPZONA
	DROP TABLE #TEMPORALFINAL
END

GO


